name: generate profile summary card

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: generate-github-profile-summary-cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 0
          EXCLUDE: ""
          AUTO_PUSH: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push svg to main branch
        run: |
          mv ./profile-summary-card-output/github_dark/0-profile-details.svg ./assets/images/github-profile-details-dark.svg
          mv ./profile-summary-card-output/github_dark/4-productive-time.svg ./assets/images/github-productive-time-dark.svg
          mv ./profile-summary-card-output/github/0-profile-details.svg ./assets/images/github-profile-details.svg
          mv ./profile-summary-card-output/github/4-productive-time.svg ./assets/images/github-productive-time.svg
          rm -rf ./profile-summary-card-output

      - name: Git Auto Commit
      # You may pin to the exact commit or the version.
      # uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          # Commit message
          commit_message: "Update profile summary card" # optional, default is Apply automatic changes
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>